### ISSUE TITLE
Besides Champlain, check GtkChamplain as well in dependency check

### ISSUE THREAD

**Issue by liangent** [robru/gottengeography#124]
When I tried to start gottengeography, I got the error message

ERROR:root:Could not find any typelib for Champlain
GottenGeography requires at least libchamplain 0.12.2

from the check "from gi.repository import Champlain". After installing gir1.2-champlain-0.12 to resolve this and some other dependencies, I can pass all dependency checks. Now if I try to start gottengeography, a traceback is printed "ImportError: cannot import name 'GtkChamplain'" from "from gi.repository import GtkChamplain, Champlain". I have to install gir1.2-gtkchamplain-0.12 to get GtkChamplain.

My OS is Debian.

**Comment by liangent** [comment]
By the way it would be better to have "(with introspection support, gir1.2-..." too in Champlain check, like:

ERROR:root:Could not find any typelib for GExiv2
GottenGeography requires at least gexiv2 0.4.90 (with introspection support, gir1.2-gexiv2-0.4)

**Comment by robru** [comment]
Ok I've added a couple more checks, please try out latest master.
