### ISSUE TITLE
gottengeography looks for data in /usr while it got installed to /usr/local

### ISSUE THREAD

**Issue by liangent** [robru/gottengeography#125]
setup.py output:

python3 setup.py install
running install
running build
running build_py
copying gg/build_info.py -> build/lib/gg
running build_scripts
running build_i18n
intltool-update -p -g gottengeography
running build_help
running install_lib
creating /usr/local/lib/python3.4/dist-packages/gg
copying build/lib/gg/build_info.py -> /usr/local/lib/python3.4/dist-packages/gg
copying build/lib/gg/app.py -> /usr/local/lib/python3.4/dist-packages/gg
copying build/lib/gg/actor.py -> /usr/local/lib/python3.4/dist-packages/gg
copying build/lib/gg/search.py -> /usr/local/lib/python3.4/dist-packages/gg
copying build/lib/gg/gpsmath.py -> /usr/local/lib/python3.4/dist-packages/gg
copying build/lib/gg/label.py -> /usr/local/lib/python3.4/dist-packages/gg
copying build/lib/gg/__init__.py -> /usr/local/lib/python3.4/dist-packages/gg
copying build/lib/gg/photos.py -> /usr/local/lib/python3.4/dist-packages/gg
copying build/lib/gg/camera.py -> /usr/local/lib/python3.4/dist-packages/gg
copying build/lib/gg/navigation.py -> /usr/local/lib/python3.4/dist-packages/gg
copying build/lib/gg/widgets.py -> /usr/local/lib/python3.4/dist-packages/gg
copying build/lib/gg/territories.py -> /usr/local/lib/python3.4/dist-packages/gg
copying build/lib/gg/drag.py -> /usr/local/lib/python3.4/dist-packages/gg
copying build/lib/gg/version.py -> /usr/local/lib/python3.4/dist-packages/gg
copying build/lib/gg/xmlfiles.py -> /usr/local/lib/python3.4/dist-packages/gg
copying build/lib/gg/common.py -> /usr/local/lib/python3.4/dist-packages/gg
byte-compiling /usr/local/lib/python3.4/dist-packages/gg/build_info.py to build_info.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/gg/app.py to app.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/gg/actor.py to actor.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/gg/search.py to search.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/gg/gpsmath.py to gpsmath.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/gg/label.py to label.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/gg/__init__.py to __init__.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/gg/photos.py to photos.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/gg/camera.py to camera.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/gg/navigation.py to navigation.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/gg/widgets.py to widgets.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/gg/territories.py to territories.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/gg/drag.py to drag.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/gg/version.py to version.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/gg/xmlfiles.py to xmlfiles.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/gg/common.py to common.cpython-34.pyc
running install_scripts
copying build/scripts-3.4/gottengeography -> /usr/local/bin
changing mode of /usr/local/bin/gottengeography to 755
running install_data
copying data/gottengeography.svg -> /usr/share/icons/hicolor/scalable/apps
copying data/ca.gottengeography.gschema.xml -> /usr/share/glib-2.0/schemas
copying data/gottengeography.desktop -> /usr/share/applications
creating /usr/local/share/doc
creating /usr/local/share/doc/gottengeography
copying README.md -> /usr/local/share/doc/gottengeography
copying AUTHORS -> /usr/local/share/doc/gottengeography
copying THANKS -> /usr/local/share/doc/gottengeography
creating /usr/local/share/gottengeography
copying data/cities.txt -> /usr/local/share/gottengeography
copying data/trackfile.ui -> /usr/local/share/gottengeography
copying data/camera.ui -> /usr/local/share/gottengeography
copying data/gottengeography.ui -> /usr/local/share/gottengeography
copying data/gottengeography.svg -> /usr/local/share/gottengeography
creating /usr/local/share/locale
creating /usr/local/share/locale/ms
creating /usr/local/share/locale/ms/LC_MESSAGES
copying build/mo/ms/LC_MESSAGES/gottengeography.mo -> /usr/local/share/locale/ms/LC_MESSAGES
creating /usr/local/share/locale/en_US
creating /usr/local/share/locale/en_US/LC_MESSAGES
copying build/mo/en_US/LC_MESSAGES/gottengeography.mo -> /usr/local/share/locale/en_US/LC_MESSAGES
creating /usr/local/share/locale/ca
creating /usr/local/share/locale/ca/LC_MESSAGES
copying build/mo/ca/LC_MESSAGES/gottengeography.mo -> /usr/local/share/locale/ca/LC_MESSAGES
creating /usr/local/share/locale/sv
creating /usr/local/share/locale/sv/LC_MESSAGES
copying build/mo/sv/LC_MESSAGES/gottengeography.mo -> /usr/local/share/locale/sv/LC_MESSAGES
creating /usr/local/share/locale/ru
creating /usr/local/share/locale/ru/LC_MESSAGES
copying build/mo/ru/LC_MESSAGES/gottengeography.mo -> /usr/local/share/locale/ru/LC_MESSAGES
creating /usr/local/share/locale/my
creating /usr/local/share/locale/my/LC_MESSAGES
copying build/mo/my/LC_MESSAGES/gottengeography.mo -> /usr/local/share/locale/my/LC_MESSAGES
creating /usr/local/share/locale/it
creating /usr/local/share/locale/it/LC_MESSAGES
copying build/mo/it/LC_MESSAGES/gottengeography.mo -> /usr/local/share/locale/it/LC_MESSAGES
creating /usr/local/share/locale/mr
creating /usr/local/share/locale/mr/LC_MESSAGES
copying build/mo/mr/LC_MESSAGES/gottengeography.mo -> /usr/local/share/locale/mr/LC_MESSAGES
creating /usr/local/share/locale/de
creating /usr/local/share/locale/de/LC_MESSAGES
copying build/mo/de/LC_MESSAGES/gottengeography.mo -> /usr/local/share/locale/de/LC_MESSAGES
creating /usr/local/share/locale/he
creating /usr/local/share/locale/he/LC_MESSAGES
copying build/mo/he/LC_MESSAGES/gottengeography.mo -> /usr/local/share/locale/he/LC_MESSAGES
creating /usr/local/share/locale/tr
creating /usr/local/share/locale/tr/LC_MESSAGES
copying build/mo/tr/LC_MESSAGES/gottengeography.mo -> /usr/local/share/locale/tr/LC_MESSAGES
creating /usr/local/share/locale/bg
creating /usr/local/share/locale/bg/LC_MESSAGES
copying build/mo/bg/LC_MESSAGES/gottengeography.mo -> /usr/local/share/locale/bg/LC_MESSAGES
creating /usr/local/share/locale/pt_BR
creating /usr/local/share/locale/pt_BR/LC_MESSAGES
copying build/mo/pt_BR/LC_MESSAGES/gottengeography.mo -> /usr/local/share/locale/pt_BR/LC_MESSAGES
creating /usr/local/share/locale/ug
creating /usr/local/share/locale/ug/LC_MESSAGES
copying build/mo/ug/LC_MESSAGES/gottengeography.mo -> /usr/local/share/locale/ug/LC_MESSAGES
creating /usr/local/share/locale/sr
creating /usr/local/share/locale/sr/LC_MESSAGES
copying build/mo/sr/LC_MESSAGES/gottengeography.mo -> /usr/local/share/locale/sr/LC_MESSAGES
creating /usr/local/share/locale/fr
creating /usr/local/share/locale/fr/LC_MESSAGES
copying build/mo/fr/LC_MESSAGES/gottengeography.mo -> /usr/local/share/locale/fr/LC_MESSAGES
creating /usr/local/share/locale/eo
creating /usr/local/share/locale/eo/LC_MESSAGES
copying build/mo/eo/LC_MESSAGES/gottengeography.mo -> /usr/local/share/locale/eo/LC_MESSAGES
creating /usr/local/share/locale/en_CA
creating /usr/local/share/locale/en_CA/LC_MESSAGES
copying build/mo/en_CA/LC_MESSAGES/gottengeography.mo -> /usr/local/share/locale/en_CA/LC_MESSAGES
creating /usr/local/share/locale/en_GB
creating /usr/local/share/locale/en_GB/LC_MESSAGES
copying build/mo/en_GB/LC_MESSAGES/gottengeography.mo -> /usr/local/share/locale/en_GB/LC_MESSAGES
creating /usr/local/share/locale/zh_CN
creating /usr/local/share/locale/zh_CN/LC_MESSAGES
copying build/mo/zh_CN/LC_MESSAGES/gottengeography.mo -> /usr/local/share/locale/zh_CN/LC_MESSAGES
creating /usr/local/share/locale/es
creating /usr/local/share/locale/es/LC_MESSAGES
copying build/mo/es/LC_MESSAGES/gottengeography.mo -> /usr/local/share/locale/es/LC_MESSAGES
creating /usr/local/share/locale/uk
creating /usr/local/share/locale/uk/LC_MESSAGES
copying build/mo/uk/LC_MESSAGES/gottengeography.mo -> /usr/local/share/locale/uk/LC_MESSAGES
creating /usr/local/share/help
creating /usr/local/share/help/C
creating /usr/local/share/help/C/gottengeography
copying help/C/shortcuts.page -> /usr/local/share/help/C/gottengeography
copying help/C/quickstart.page -> /usr/local/share/help/C/gottengeography
copying help/C/index.page -> /usr/local/share/help/C/gottengeography
copying help/C/timezones.page -> /usr/local/share/help/C/gottengeography
creating /usr/local/share/help/C/gottengeography/figures
copying help/C/figures/02-load-gps.png -> /usr/local/share/help/C/gottengeography/figures
copying help/C/figures/03-load-photos.png -> /usr/local/share/help/C/gottengeography/figures
copying help/C/figures/tz-system.png -> /usr/local/share/help/C/gottengeography/figures
copying help/C/figures/tz-utc.png -> /usr/local/share/help/C/gottengeography/figures
copying help/C/figures/tz-local.png -> /usr/local/share/help/C/gottengeography/figures
copying help/C/figures/06-manual.png -> /usr/local/share/help/C/gottengeography/figures
copying help/C/figures/07-viewing.png -> /usr/local/share/help/C/gottengeography/figures
copying help/C/figures/gpx.png -> /usr/local/share/help/C/gottengeography/figures
copying help/C/figures/01-edmonton.png -> /usr/local/share/help/C/gottengeography/figures
copying help/C/figures/05-selection.png -> /usr/local/share/help/C/gottengeography/figures
copying help/C/figures/tz-manual-canada.png -> /usr/local/share/help/C/gottengeography/figures
copying help/C/figures/04-camera-offset.png -> /usr/local/share/help/C/gottengeography/figures
copying help/C/figures/tz-manual-america.png -> /usr/local/share/help/C/gottengeography/figures
glib-compile-schemas /usr/share/glib-2.0/schemas/
running install_egg_info
Writing /usr/local/lib/python3.4/dist-packages/gottengeography-2.5.egg-info

gottengeography command output:

Traceback (most recent call last):
  File "/usr/local/bin/gottengeography", line 71, in <module>
    from gg.app import GottenGeography
  File "/usr/local/lib/python3.4/dist-packages/gg/app.py", line 26, in <module>
    from gg.camera import Camera
  File "/usr/local/lib/python3.4/dist-packages/gg/camera.py", line 30, in <module>
    from gg.widgets import Builder, Widgets
  File "/usr/local/lib/python3.4/dist-packages/gg/widgets.py", line 78, in <module>
    class Widgets(Builder):
  File "/usr/local/lib/python3.4/dist-packages/gg/common.py", line 62, in singleton
    return single()
  File "/usr/local/lib/python3.4/dist-packages/gg/widgets.py", line 84, in __init__
    Builder.__init__(self)
  File "/usr/local/lib/python3.4/dist-packages/gg/widgets.py", line 43, in __init__
    self.add_from_file(join(PKG_DATA_DIR, filename + '.ui'))
gi._glib.GError: Failed to open file '/usr/share/gottengeography/gottengeography.ui': No such file or directory

(I worked around it with `ln -s /usr/local/share/gottengeography /usr/share/gottengeography`. Is there a better workaround?)

**Comment by robru** [comment]
Ah, this seems to be a side-effect of 1f998737b337ff627c1cebb963171cc973f7e31d. Previously, all installs went to /usr. However `install_layout=deb` was breaking pip inside TravisCI so I had to drop that. As a side effect, now only the deb package installs to /usr and 'setup.py install' installs to /usr/local. I assumed distutils would handle the prefix case for me, but I guess not.

Anyway I've fixed it now so that it correctly looks for it's files in /usr/local if installed that way. Let me know if you have any further problems.
