### ISSUE TITLE
"TypeError: GObject.__init__() takes exactly 0 arguments (1 given)" after upgrade from Ubuntu 13.10 to 14.10

### ISSUE THREAD

**Issue by Hooloovoo** [robru/gottengeography#126]
Hi,

I just upgraded my machine from Ubuntu 13.10 to Ubuntu 14.10. Now, when I select photos in the file chooser, or drag them in, the program crashes, saying:
$ gottengeography

(gottengeography:13818): Gtk-WARNING **: Unsupported type tag for GtkSizeGroup: placeholder

(gottengeography:13818): Gtk-WARNING **: Unsupported type tag for GtkSizeGroup: placeholder

(gottengeography:13818): Gtk-WARNING **: Unsupported type tag for GtkSizeGroup: placeholder

(gottengeography:13818): Gtk-WARNING **: Unsupported type tag for GtkSizeGroup: placeholder

(gottengeography:13818): Gtk-WARNING **: Unsupported type tag for GtkSizeGroup: placeholder

(gottengeography:13818): Gtk-WARNING **: Unsupported type tag for GtkSizeGroup: placeholder

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gg/app.py", line 228, in add_files_dialog
    self.open_files(Widgets.open.get_filenames())
  File "/usr/lib/python3/dist-packages/gg/app.py", line 168, in open_files
    Photograph.load_from_file(name)
  File "/usr/lib/python3/dist-packages/gg/common.py", line 148, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gg/photos.py", line 179, in load_from_file
    photo = Photograph(uri)
  File "/usr/lib/python3/dist-packages/gg/common.py", line 123, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gg/photos.py", line 210, in __init__
    self.thumb = fetch_thumbnail(filename)
  File "/usr/lib/python3/dist-packages/gg/photos.py", line 101, in fetch_thumbnail
    exif = GExiv2.Metadata(filename)
TypeError: GObject.__init__() takes exactly 0 arguments (1 given)

I set up the ppa again and redownloaded to make sure I had the correct version for this Ubuntu release. My version info is:
$ dpkg -s gottengeography
Package: gottengeography
Status: install ok installed
Priority: extra
Section: graphics
Installed-Size: 9522
Maintainer: Robert Bruce Park <robru@gottengeography.ca>
Architecture: all
Version: 3:201503022031~ubuntu14.10.1
Depends: gir1.2-champlain-0.12, gir1.2-clutter-1.0, gir1.2-gdkpixbuf-2.0, gir1.2-gexiv2-0.10 | gir1.2-gexiv2-0.4, gir1.2-glib-2.0, gir1.2-gtk-3.0, gir1.2-gtkchamplain-0.12 (>= 0.12.2), gir1.2-gtkclutter-1.0, python3-dateutil, python3-gi, dconf-gsettings-backend | gsettings-backend, python3, python3:any (>= 3.3.2-2~)
Description: Automagically geotag photos with GPX data.
 GottenGeography is a GNOME application that aims to make it easy to record
 geotags into your photographs. If you have a GPS device, GottenGeography can
 load it's GPX data and directly compare timestamps between the GPX data and the
 photos, automatically determining where each photo was taken. If you do not
 have a GPS device, GottenGeography allows you to manually place photos onto a
 map, and then record those locations into the photos.
Homepage: http://gottengeography.ca

I assume that this is related to:
https://bugs.launchpad.net/ubuntu/+source/gexiv2/+bug/1312457
but as far as I can see it should be fixed now. Perhaps something hasn't updated properly because I did an upgrade instead of a fresh install. Any thoughts greatly appreciated, as I use this program all the time!

**Comment by robru** [comment]
Hmmm, yes this issue should have been fixed long ago... Can you please show me the contents of your `GExiv2.py` file? Eg run this and paste the output somewhere:

    $ cat /usr/lib/python3/dist-packages/gi/overrides/GExiv2.py

also can you show me the output of `apt-cache policy 'gir.*gexiv'` please?

**Comment by Hooloovoo** [comment]
$ cat /usr/lib/python3/dist-packages/gi/overrides/GExiv2.py
# -*- Mode: Python; py-indent-offset: 4 -*-
# vim: tabstop=4 shiftwidth=4 expandtab
#
# Copyright (C) 2012 Robert Park <rbpark@exolucere.ca>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
# USA

from datetime import datetime
from fractions import Fraction

from gi import _glib
from gi.repository import GObject
from ..overrides import override
from ..importer import modules

GExiv2 = modules['GExiv2']._introspection_module
__all__ = []

DATE_FORMAT = '%Y:%m:%d %H:%M:%S'
MAX_INT = 2**31 - 1

@override
class Metadata(GExiv2.Metadata):
    def __init__(self, path=None):
        super(Metadata, self).__init__()
        self._path = path
        if path is not None:
            self.open_path(path)
    
    def open_path(self, path):
        self._path = path
        super(Metadata, self).open_path(path)
    
    def save_file(self, path=None):
        super(Metadata, self).save_file(path or self._path)
    
    def get_date_time(self):
        datestring = super(Metadata, self).get_date_time()
        if datestring is not None:
            return datetime.strptime(datestring, DATE_FORMAT)
    
    def set_date_time(self, value):
        super(Metadata, self).set_date_time(value.strftime(DATE_FORMAT))
    
    def get_exposure_time(self):
        num, denom = super(Metadata, self).get_exposure_time()
        return Fraction(num, denom) if denom else None
    
    def get_exif_tag_rational(self, key):
        num, denom = super(Metadata, self).get_exif_tag_rational(key)
        return Fraction(num, denom) if denom else None
    
    def set_exif_tag_rational(self, key, fraction):
        limit = MAX_INT
        while True:
            try:
                return super(Metadata, self).set_exif_tag_rational(
                    key, fraction.numerator, fraction.denominator)
            except ValueError:
                fraction = fraction.limit_denominator(limit)
                limit = int(limit / 2)
    
    def get_tags(self):
        return self.get_exif_tags() + self.get_iptc_tags() + self.get_xmp_tags()
    
    def get(self, key, default=None):
        return self.get_tag_string(key) if self.has_tag(key) else default
    
    def __iter__(self):
        return iter(self.get_tags())
    
    def __contains__(self, key):
        return self.has_tag(key)
    
    def __len__(self):
        return len(self.get_tags())
    
    def __getitem__(self, key):
        if self.has_tag(key):
            return self.get_tag_string(key)
        else:
            raise KeyError('%s: Unknown tag' % key)
    
    def __delitem__(self, key):
        if self.has_tag(key):
            self.clear_tag(key)
        else:
            raise KeyError('%s: Unknown tag' % key)
    
    __setitem__ = GExiv2.Metadata.set_tag_string

__all__.append('Metadata')

if not GExiv2.initialize():
    raise RuntimeError("GExiv2 couldn't be initialized")

**Comment by Hooloovoo** [comment]
$ apt-cache policy 'gir.*gexiv'
gir1.2-gexiv2-0.4:
  Installed: 0.6.1-2
  Candidate: 0.6.1-2
  Version table:
 *** 0.6.1-2 0
        100 /var/lib/dpkg/status
gir1.2-gexiv2-0.10:
  Installed: (none)
  Candidate: 0.10.1-1build1
  Version table:
     0.10.1-1build1 0
        500 http://gb.archive.ubuntu.com/ubuntu/ utopic/main amd64 Packages

**Comment by robru** [comment]
Ah, indeed you have the old version of gexiv2. This should fix the issue for you:

```
$ sudo apt-get purge gir1.2-gexiv2-0.4
$ sudo apt-get install gir1.2-gexiv2-0.10
```

I'll update the packaging to indicate that 0.10 is now required.

**Comment by Hooloovoo** [comment]
All sorted now - thanks!!!

**Comment by robru** [comment]
You're welcome! Thanks for using GottenGeography ;-)

**Comment by anarey** [comment]
I fixed this problem in Fedora 20 I installed the libgexiv2 packet (Python3 bindings for libgexiv2) :)
